name: QuakeC Round 100 Tests
on: [pull_request]
jobs:
  Round-100-Tests:
    name: Run Round 100 Tests
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.10
      options: --shm-size=8192m
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Wait for GitHub to keep up..
        run: sleep 2s
        shell: bash
      - name: Run Round 100 Script
        run: |
          bash testing/run_map_tests.sh
